name: Deploy to CloudFormation

on:
  push:
    branches:
      - main  # Change to the branch you want to trigger the workflow

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: AWS  # Specify the environment
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE16: true  # Force actions to use Node.js 20

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1  # Change to your AWS region

    - name: Deploy CloudFormation stack
      run: |
        aws cloudformation deploy \
          --template-file ./cloudformation/workshop4\ \(2\)\ \(1\).yaml \  # Adjusted path
          --stack-name my-cloudformation-stack \  # Change to your stack name
          --capabilities CAPABILITY_NAMED_IAM
